Add support for custom URLs for each side
bryik/aframe-cubemap-component pull request #4
Opened 2017-05-12 10:12 UTC by ip

2017-05-13 00:53 UTC, bryik requested changes
This looks like a nice feature.

Would you mind adding an example as well?

2017-05-13 00:53 UTC, bryik commented on index.js
> +    if (srcPath === '')
Style-wise I prefer to always use brackets in `if` statements (even if they're not strictly necessary).

2017-05-13 00:53 UTC, bryik commented on index.js
> +      ];
brackets here too, please

2017-05-13 00:54 UTC, bryik commented on index.js
> +    var urls = this.data.urls;
You can just do `data.urls;`

2017-05-13 21:24 UTC, ip commented
Okay, I'll fix these a bit later and add an example.

2020-05-03 21:37 UTC, bryik commented
Closing as this has been open for a while.

2020-05-03 21:37 UTC, closed without merging