Update compatibility with threejs
bryik/aframe-cubemap-component pull request #46
Opened 2024-08-27 19:32 UTC by AryehMischel

Hi, I noticed that the component was no longer working in the latest A-Frame releases (1.4.0 and up). After some poking around, I found the issue has to do with two updates to three.js.
 **1.** BoxBufferGeometry has been deprecated. [link](https://github.com/mrdoob/three.js/wiki/Migration-Guide#144--145)
 **2.** The cube shader in ShaderLib has different uniforms now. envMap is now tCube.  [link](https://github.com/mrdoob/three.js/wiki/Migration-Guide#145--146) 
It only took a few changes to get everything up to speed. I changed BoxBufferGeometry to BoxGeometry, and I added some logic to make sure we are using the correct uniforms. Now everything works like a charm! I made a PR, so please take a look when you get a chance. I really like this component and I think it would be great if it stayed available for future use! Cheers

2024-09-04 02:11 UTC, bryik commented
Nice, thanks for the MR! I'll take a look. 

Sorry for the late reply, my GitHub notifications weren't coming through.

2024-09-04 03:16 UTC, bryik requested changes
Looks good, just a few nitpicks! Thanks for the MR!

2024-09-04 03:16 UTC, bryik commented on index.js
> +    //they changed the name of the uniform from tCube to envMap, this variable helps us keep track of the name across three js versions
Some minor style edits to this comment.

```suggestion
    // Starting in Three.js v146, `envMap` changed to `tCube`.
    // This variable helps us keep track of the name across Three.js versions.
    // https://github.com/mrdoob/three.js/wiki/Migration-Guide#145--146
```

2024-09-04 03:16 UTC, bryik commented on index.js
> +  //   this.material.uniforms["envMap"].value = new THREE.Texture();
I think this commented out line can be removed?

```suggestion
```

2024-09-05 15:19 UTC, AryehMischel commented
Sure no problem. I made those edits, so it should be good to merge 👍

2024-09-06 18:09 UTC, merged

2024-09-06 18:09 UTC, bryik commented
Thanks!